name: CI test

on: [push]

env:
  NODE_VERSION: 16.x

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run linters
        run: |
          node_modules/.bin/eslint src --ext .js,.jsx,.ts,.tsx
          node_modules/.bin/prettier --write src/**/*.{.js,.jsx,ts,tsx}
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
